### ISSUE TITLE
Where is Theme class

### ISSUE THREAD

**Issue by ivanzhang** [intentor/laravel-theme#2]
when you use Theme::set('theme_name')...

and when i test it in laravel 5.1, got exception message: 

**FatalErrorException in Container.php line 1057:**

**Maximum function nesting level of '100' reached, aborting!**

**Comment by intentor** [comment]
Hello!

Are you using the latest version (1.2), which has full support for Laravel 5.1+?

Given this exception is usually related to recursion and there's no (at least directly) recursion taking place on the component, can you please provide some more context based on the app your developing?

Thanks!

**Comment by intentor** [comment]
This issue will be closed. If you have any more information regarding the problem, please reopen it.
